# Generated by Django 4.2.5 on 2023-10-24 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('ten_phong', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('gia_phong', models.IntegerField()),
                ('gia_nuoc', models.IntegerField()),
                ('gia_dien', models.IntegerField()),
                ('mo_ta', models.TextField()),
                ('anh_phong', models.ImageField(blank=True, upload_to='images/')),
                ('tien_coc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trang_thai', models.CharField(choices=[('trống', 'Trống'), ('đã thuê', 'Đã Thuê')], default='trống', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThuePhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateField()),
                ('tien_no', models.DecimalField(decimal_places=2, max_digits=10)),
                ('so_dien_thoai_nhan_hoa_don', models.CharField(max_length=10)),
                ('ten_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.phong')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('can_cuoc', models.CharField(max_length=12)),
                ('bien_so_xe', models.CharField(blank=True, max_length=10)),
                ('so_dien_thoai', models.CharField(max_length=10)),
                ('van_tay', models.CharField(blank=True, default='chưa có', max_length=100)),
                ('ten_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.phong')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_co_hoa_don', models.DateField(blank=True)),
                ('ngay_thanh_toan', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('chưa thanh toán', 'Chưa Thanh Toán'), ('đã thanh toán', 'Đã Thanh Toán')], default='chưa thanh toán', max_length=15)),
                ('so_dien_dau', models.IntegerField(blank=True)),
                ('so_dien_cuoi', models.IntegerField()),
                ('tien_dien', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('so_nuoc_dau', models.IntegerField(blank=True)),
                ('so_nuoc_cuoi', models.IntegerField()),
                ('tong_tien_nuoc', models.DecimalField(blank=True, decimal_places=2, default=20000, max_digits=10)),
                ('tong_cong', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ten_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.phong')),
            ],
        ),
    ]
