# Generated by Django 4.2.5 on 2023-10-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='chi_so_dien',
            field=models.IntegerField(default=0),
        ),
    ]
