# Generated by Django 4.2.5 on 2023-10-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0002_phong_chi_so_dien'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='chi_so_nuoc',
            field=models.IntegerField(default=0),
        ),
    ]
